###fazRequest
GET http://localhost:8080/topicos

###fazRequestId
GET http://localhost:8080/topicos/30


###fazUpdateId
PUT http://localhost:8080/topicos/3
Content-Type: application/json

{
  "titulo":"Atualizado",
  "mensagem":"Mensagem nova"
}



###fazDeleteId
DELETE http://localhost:8080/topicos/30
Content-Type: application/json


